In [1]:
import torch
import numpy as np

## Creating various Tensors

In [3]:
def print_tensor(tensor) -> None:
    print(tensor)

In [4]:
def get_tensor_attributes(tensor) -> None:
    print(f'Shape: {tensor.shape}')
    print(f'No. of Dimentions: {tensor.ndim}')
    print(f'Datatype: {tensor.dtype}')
    print(f'Device: {tensor.device}')

In [5]:
# Scaler
scaler = torch.tensor(7)

print_tensor(scaler)
print()
get_tensor_attributes(scaler)

tensor(7)

Shape: torch.Size([])
No. of Dimentions: 0
Datatype: torch.int64
Device: cpu


In [ ]:
# vector
vector = torch.tensor([1, 2])

print_tensor(vector)
print()
get_tensor_attributes(vector)

tensor([1, 2])

Shape: torch.Size([2])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu


In [ ]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])

print_tensor(MATRIX)
print()
get_tensor_attributes(MATRIX)

tensor([[1, 2],
        [3, 4]])

Shape: torch.Size([2, 2])
No. of Dimentions: 2
Datatype: torch.int64
Device: cpu


In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print_tensor(TENSOR)
print()
get_tensor_attributes(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Shape: torch.Size([1, 3, 3])
No. of Dimentions: 3
Datatype: torch.int64
Device: cpu


## Random Tensors

Why?

Important because the way many nn learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data... Repeat`

In [ ]:
# create a random tensor of shape/size (3, 4)
random_tensor = torch.rand(size=(3, 4))

print_tensor(random_tensor)
print()
get_tensor_attributes(random_tensor)

tensor([[0.1163, 0.0126, 0.4437, 0.9567],
        [0.5189, 0.0665, 0.2733, 0.9440],
        [0.9965, 0.0648, 0.5917, 0.3631]])

Shape: torch.Size([3, 4])
No. of Dimentions: 2
Datatype: torch.float32
Device: cpu


In [ ]:
# create a random tensor with similar shape to an image tensors (height, width, color_channels)

random_image_size_tensor = torch.rand(size=(224, 224, 3))

# print_tensor(random_image_size_tensor)
print()
get_tensor_attributes(random_image_size_tensor)


Shape: torch.Size([224, 224, 3])
No. of Dimentions: 3
Datatype: torch.float32
Device: cpu


## Tensors of zeros and ones

In [ ]:
# creating a tensor of zeros
zeros = torch.zeros(size=(3, 4))

print_tensor(zeros)
print()
get_tensor_attributes(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Shape: torch.Size([3, 4])
No. of Dimentions: 2
Datatype: torch.float32
Device: cpu


In [ ]:
# creating a tensor of ones
ones = torch.ones(size=(3, 4))

print_tensor(ones)
print()
get_tensor_attributes(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Shape: torch.Size([3, 4])
No. of Dimentions: 2
Datatype: torch.float32
Device: cpu


## Tensors in a range

In [ ]:
# creating a tensor in a range
one_to_ten = torch.arange(start=1, end=11, step=1)

print_tensor(one_to_ten)
print()
get_tensor_attributes(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Shape: torch.Size([10])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu


## Tensors-Like

In [ ]:
# creating zeros tensor-like one_to_ten
ten_zeros = torch.zeros_like(input=one_to_ten)

print_tensor(ten_zeros)
print()
get_tensor_attributes(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Shape: torch.Size([10])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu


In [ ]:
# creating ones tensor-like one_to_ten
ten_ones = torch.ones_like(input=one_to_ten)

print_tensor(ten_ones)
print()
get_tensor_attributes(ten_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Shape: torch.Size([10])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu


## Tensor DataTypes

32-bit floating point: `torch.float32`

64-bit floating point: `torch.float64`

16-bit floating point 1: `torch.float16`

16-bit floating point 2: `torch.bfloat16`

32-bit complex: `torch.complex32`

64-bit complex: `torch.complex64`

128-bit complex: `torch.complex128`

8-bit integer (unsigned): `torch.uint8`

16-bit integer (unsigned): `torch.uint16`

32-bit integer (unsigned): `torch.uint32`

64-bit integer (unsigned): `torch.uint64`

8-bit integer (signed): `torch.int8`

16-bit integer (signed): `torch.int16`

32-bit integer (signed): `torch.int32`

64-bit integer (signed): `torch.int64`

Boolean: `torch.bool`

In [ ]:
# creating a float_32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor. e.g. float32, float64, etc.
                               device=None, # device on which the tensor is. e.g. 'cpu', 'cuda', etc.
                               requires_grad=False # tells if gradients need to be computed for the tensor...
                               )

print_tensor(float_32_tensor)
print()
get_tensor_attributes(float_32_tensor)

tensor([3., 6., 9.])

Shape: torch.Size([3])
No. of Dimentions: 1
Datatype: torch.float32
Device: cpu


In [ ]:
# creating a float16 tensors with values in float_32_tensor
float_16_tensor = float_32_tensor.type(torch.float16)

print_tensor(float_16_tensor)
print()
get_tensor_attributes(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)

Shape: torch.Size([3])
No. of Dimentions: 1
Datatype: torch.float16
Device: cpu


## Tensor Operations

1. Addition
2. Subtraction
3. Division
4. Multiplication (Element Wise)
5. Dot Product (Matrix Multiplication)

    There are two main rules for matrix multiplication:
    * The inner dimentions of the tensor should match
    * The resulting tensor has the shape of outer dimentions


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

In [ ]:
# addition of tensors
tensor + 10

tensor([11, 12, 13])

In [ ]:
# subtraction of tensors
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# division of tensors
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# element wise nultiplication of tensors
tensor * 10

tensor([10, 20, 30])

In [ ]:
# dot product
print(torch.matmul(tensor, tensor2))
get_tensor_attributes(torch.matmul(tensor, tensor2))

tensor(32)
Shape: torch.Size([])
No. of Dimentions: 0
Datatype: torch.int64
Device: cpu


In [ ]:
# let's create two random tensors
tensor_1 = torch.arange(start=1, end=7).reshape(2, 3)
tensor_2 = torch.arange(start=11, end=17).reshape(3, 2)

get_tensor_attributes(tensor_1)
print()
get_tensor_attributes(tensor_2)

Shape: torch.Size([2, 3])
No. of Dimentions: 2
Datatype: torch.int64
Device: cpu

Shape: torch.Size([3, 2])
No. of Dimentions: 2
Datatype: torch.int64
Device: cpu


In [ ]:
# let's multiply those two tensors
print(tensor_1)
print()

print(tensor_2)
print()

print(torch.matmul(tensor_1, tensor_2))

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[11, 12],
        [13, 14],
        [15, 16]])

tensor([[ 82,  88],
        [199, 214]])


## Tensor Transpose

switches the axis of a tensor

In [ ]:
# transposing the tensor_1
print(tensor_1.shape)
print(tensor_1.T.shape)

torch.Size([2, 3])
torch.Size([3, 2])


## Tensor Aggregation

In [ ]:
## finding min and max value within a tensor
print(f'Min of tensor: {torch.min(tensor_1)}')
print(f'Max of tensor: {torch.max(tensor_1)}')

Min of tensor: 1
Max of tensor: 6


In [ ]:
# getting mean of a tensor
# torch.mean(one_to_ten) # the code will throw an error since torch.mean requires the tensor to be a float or complex datatype
torch.mean(one_to_ten.type(torch.float32))

tensor(5.5000)

In [ ]:
# getting sum of values in a tensor
torch.sum(one_to_ten)

tensor(55)

Positional min and max of a tensor:

In [ ]:
# find the position (index) in tensor that has the minimum value
print(torch.argmin(one_to_ten))

# find the position (index) in tensor that has the maximum value
print(torch.argmax(one_to_ten))

tensor(0)
tensor(9)


## Reshaping, Viewing and Stacking Tensors

* Reshaping: reshape the tensor to defined shape
* View: return view of given tensor of certain shape but keep the memory as original tensor
* Stacking: combine multiple tensors upon each other
* Squeezing: remove all `1` dimention from a tensor
* Unsqueezing: add `1` dimention to a  tensor
* Permute: return a view of input with dimentions permuted (swapped) in a certain way

In [ ]:
X = torch.arange(1.,10.)
get_tensor_attributes(X)

Shape: torch.Size([9])
No. of Dimentions: 1
Datatype: torch.float32
Device: cpu


In [ ]:
# reshape the tensor
X_reshaped = X.reshape(1, 9)
get_tensor_attributes(X_reshaped)

Shape: torch.Size([1, 9])
No. of Dimentions: 2
Datatype: torch.float32
Device: cpu


In [ ]:
# change the view
z = X.view(1, 9)
get_tensor_attributes(z)

# here, changing z changes X as well because a view of a tensor shares the same memory as the original input

Shape: torch.Size([1, 9])
No. of Dimentions: 2
Datatype: torch.float32
Device: cpu


In [ ]:
# stack tensors on top of each other
torch.stack([X, X, X, X], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.stack([X, X, X, X], dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze
print(f'Original Shape: {X_reshaped.shape}')
print(f'Squeezed Tensor: {torch.squeeze(X_reshaped).shape}')

Original Shape: torch.Size([1, 9])
Squeezed Tensor: torch.Size([9])


In [ ]:
# unsqueeze
print(f'Original Shape: {X_reshaped.shape}')
print(f'Unsqueezed Tensor: {torch.unsqueeze(X_reshaped, dim=0).shape}')

Original Shape: torch.Size([1, 9])
Unsqueezed Tensor: torch.Size([1, 1, 9])


In [ ]:
# permute an image tensor
image_tensor = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

print(f'Original Image Tensor Shape: {image_tensor.shape}')
print(f'Permuted Image Tensor Shape: {torch.permute(image_tensor, dims=(2, 0, 1)).shape}')

Original Image Tensor Shape: torch.Size([224, 224, 3])
Permuted Image Tensor Shape: torch.Size([3, 224, 224])


## Tensor Indexing

PyTorch Tensor Indexing is similar to NumPy Indexing

## PyTorch Tensors and NumPy

In [ ]:
# turn a numpy array in pytorch tensor
array = np.arange(1.0, 8.0)
print(f'Numpy array dtype: {array.dtype}')
print()

tensor = torch.from_numpy(array) # the tensor is converted to the default numpy datatype
get_tensor_attributes(tensor)

Numpy array dtype: float64

Shape: torch.Size([7])
No. of Dimentions: 1
Datatype: torch.float64
Device: cpu


## PyTorch Reproducebility Like `np.random.seed()`

this helps reduce the randomness in the learning of neural networks

In [ ]:
# set the pytorch random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# creating two random tensors
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Accessing GPUs using PyTorch

### Getting a GPU

1) Use Google Colab GPUs

2) Use own GPU Setup

3) Use cloud computing

### Steps to run code on a GPU on Google Colab

1) Select a GPU Runtime from the runtime option

2) Check the available hardware using `!nvidia-smi`

3) Check for GPU access using PyTorch using `torch.cuda.is_available()`

In [ ]:
!nvidia-smi

Wed Sep 18 17:45:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# check gpu availability using PyTorch
print('GPU is available!!' if torch.cuda.is_available() else 'GPU is not available!!')

GPU is available!!


### Setting up device agnostic code

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# cout the number of GPUs
torch.cuda.device_count()

1

## Putting Tensors/Models on the GPUs for faster operations

In [ ]:
# create tensor on cpu
tensor = torch.tensor([1, 2, 3])

get_tensor_attributes(tensor)

Shape: torch.Size([3])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu


In [ ]:
# move tensor to the gpu
tensor_on_gpu = tensor.to(device)

get_tensor_attributes(tensor_on_gpu)

Shape: torch.Size([3])
No. of Dimentions: 1
Datatype: torch.int64
Device: cuda:0


In [ ]:
# moving tensor back to the cpu
# Usecase: NumPy Arrays don't work on GPU
tensor_on_cpu = tensor_on_gpu.cpu()

get_tensor_attributes(tensor_on_cpu)

Shape: torch.Size([3])
No. of Dimentions: 1
Datatype: torch.int64
Device: cpu
